exports.__esModule = !0;

var n = "id code name title salePrice itemImageList { picUrl }", e = " \n   id code type status createdAt expiredAt\n   member { name nickName mobile id avatarUrl }\n   team { id status endedAt limitNumber members { id } }\n   payment { amount status }\n   shipment { address { countryName provinceName cityName districtName detailInfo nationalCode postalCode consigneeName consigneePhoneNumber } }\n   invoice {  \n  province city district address company companyAddress bank bankAccount content \n  invoiceType tittle name mail mobile taxCode telephone mode \n   }\n   items {\n     quantity\n     price\n     productSku {\n       id status salePrice\n       attrSaleList {\n         attributeFrontName\n         attributeValueList { attributeValueFrontName attributeValueName }\n       }\n       product { " + n + " }\n     }\n   }\n  ";

exports.default = {
    nano: function(n) {
        n = String(n).replace(/[\n\r]/g, ""), n = Array.isArray(n) ? n.join("") : n;
        var e = /(query|mutation) ?([\w\d-_]+)? ?\(.*?\)? \{/.exec(n);
        return function(t) {
            var a = {
                query: n
            };
            return t && (a.variables = t), e && e.length && e[2] && (a.operationName = e[2]), 
            JSON.stringify(a);
        };
    },
    paramsTemplate: {
        orderList: "\n    query($accessToken: String!, $status: MarketingOrderStatus, $first: Int, $after: String, $pintuanTeamId: String) {\n      customer(accessToken: $accessToken) {\n        myMarketingOrdersConnection (status: $status, after: $after, first: $first, pintuanTeamId: $pintuanTeamId) {\n          edges { node { " + e + " } }\n          pageInfo { startCursor endCursor }\n        }\n      }\n    }",
        orderDetail: "\n    query($accessToken: String!, $id: String!) {\n      customer(accessToken: $accessToken) {\n        myMarketingOrder (id: $id) { " + e + " }\n      }\n    }",
        orderDetailSupplement: "\n    query($accessToken: String!, $id: String!) {\n      customer(accessToken: $accessToken) {\n        myMarketingOrder (id: $id) {  \n   id code type status\n   member { name nickName mobile id avatarUrl }\n   team { id status endedAt limitNumber members { id } }\n   }\n      }\n    }",
        teamDetail: "\n    query($tenantCode: String!, $id: String!) {\n      pintuanTeam(tenantCode: $tenantCode, id: $id) {\n        id code status startedAt endedAt limitNumber currentNumber \n        campaign { id code name status availablePeriod { start end } productSkus { id pintuanPrice } }\n        productSkus { id code salePrice pintuanPrice creatorPrice \n          product { code }\n        }\n        product { \n          " + n + " \n          completedPintuanTeamsCount\n          ongoingTeams {\n            id code endedAt limitNumber currentNumber \n            creator { id code nickName avatarUrl }\n          }\n        }\n        creator { id name code}\n        members { id code name mobile avatarUrl nickName }\n      }\n    }\n    ",
        joinTeam: "\n    mutation($accessToken: String!, $input: PintuanTeamJoinInput!) {\n      joinPintuanTeam(accessToken: $accessToken, input: $input) {\n        marketingOrder {\n          id\n          code\n        }\n        pintuanTeam {\n          id\n          code\n        }\n      }\n    }\n    ",
        createTeam: "\n    mutation($accessToken: String!, $input: PintuanTeamCreateInput!) {\n      createPintuanTeam(accessToken: $accessToken, input: $input) {\n        marketingOrder {\n          id\n          code\n        }\n        pintuanTeam {\n          id\n          code\n        }\n      }\n    }\n    ",
        products: "\n    query($tenantCode: String!, $productIds: [String!]!) {\n      products(tenantCode: $tenantCode, productIds: $productIds) {\n        " + n + "\n        listPrice\n        completedPintuanTeamsCount\n        ongoingTeams {\n          id\n          code\n          creator {\n            nickName\n            avatarUrl\n            code\n          }\n          limitNumber\n          currentNumber\n          endedAt\n          pintuanCampaignProduct {\n            campaign {\n              name\n            }\n          }\n        }\n        campaign {\n          id\n          code\n          name\n          availablePeriod {\n            start\n            end\n          }\n          ... on PintuanCampaign {\n            limitNumber\n            productSkus {\n              code\n              pintuanPrice\n              creatorPrice\n              product{\n                code\n              }\n            }\n          }\n        }\n      }\n    }\n    ",
        campaignList: "\n    query($type: CampaignType!, $namePrefix: String, $status: CampaignStatus, $first: Int, $after: String){\n      shop{\n        campaigns(type:$type, status:$status, namePrefix: $namePrefix, first: $first, after: $after){\n          edges{\n            node{\n              ... on PintuanCampaign{\n                id\n                code\n                name\n                status\n                limitNumber\n                availablePeriod{\n                  start\n                  end\n                }\n                productSkus\n                {\n                  id\n                  code\n                  listPrice\n                  pintuanPrice\n                  \n                  attrSaleList {\n                    attributeFrontName\n                    attributeValueList { attributeValueFrontName attributeValueName }\n                  }\n\n                  product\n                  {\n                    id\n                    code\n                    name\n                    itemImageList\n                    {\n                      picUrl\n                    }\n                    completedPintuanTeamsCount\n                    \n                    attrSaleList {\n                      attributeFrontName\n                      attributeValueList { attributeValueFrontName attributeValueName }\n                    }\n                  }\n                }\n              }\n            }\n          }\n          pageInfo{\n            startCursor\n            pageIndex: endCursor\n            hasNextPage\n            hasPreviousPage\n          }\n        }\n      }\n    }\n    ",
        campaign: "\n    query($tenantCode: String!, $id: String!) {\n      pintuanCampaign(tenantCode: $tenantCode, id: $id) {\n        id\n        name\n        availablePeriod {\n          start\n          end\n        }\n        productSkus {\n          code\n          pintuanPrice\n          creatorPrice\n        }\n      }\n    }\n    ",
        pay: "\n    mutation($accessToken: String!, $id: String!, $paymentProvider: PaymentProvider!, $openid: String) {\n      prepayMarketingOrder(accessToken: $accessToken, id: $id, openid: $openid, paymentProvider: $paymentProvider) {\n        ...on WeixinMiniprogramPaymentRequest{\n          appId\n          timeStamp\n          nonceStr\n          package\n          signType\n          paySign\n        }\n      }\n    }\n    ",
        byCodes: "\n    query byCodes($typename: String!,$codes: [String!]!) {\n      order: byCodes(typename:$typename,codes:$codes){\n        ...on MarketingOrder{\n          status,\n          code\n        }\n      }\n    }\n    "
    },
    formatParams: function(n, e) {
        return this.nano(this.paramsTemplate[n])(e);
    }
};